" Load custom colors
let s:VIM_DIR = fnamemodify($MYVIMRC, ':h')
if filereadable(s:VIM_DIR . '/colors/wallbash.vim')
    colorscheme wallbash
endif

" Adding your custom colorschem
"colorscheme zaibatsu "the only nice built-in colorscheme 

" remaps
"inoremap <C-c> <Esc>
"nnoremap <leader>ff :w<CR>
"nnoremap ; :
"vnoremap ; :
