animations {
    enabled = true
    bezier = emphasizedDecel, 0.05, 0.7, 0.1, 1
    bezier = emphasizedAccel, 0.3, 0, 0.8, 0.15
    bezier = standardDecel, 0, 0, 0, 1
    bezier = menu_decel, 0.1, 1, 0, 1
    bezier = menu_accel, 0.52, 0.03, 0.72, 0.08
    bezier = stall, 1, -0.1, 0.7, 0.85
    animation = windowsIn, 1, 3, emphasizedDecel, popin 80%
    animation = windowsOut, 1, 2, emphasizedDecel, popin 90%
    animation = windowsMove, 1, 3, emphasizedDecel, slide
    animation = fadeIn, 1, 3, emphasizedDecel
    animation = fadeOut, 1, 2, emphasizedDecel
    animation = border, 1, 10, emphasizedDecel
    animation = layersIn, 1, 2.7, emphasizedDecel, popin 93%
    animation = layersOut, 1, 2.4, menu_accel, popin 94%
    animation = fadeLayersIn, 1, 0.5, menu_decel
    animation = fadeLayersOut, 1, 2.7, stall
    animation = workspaces, 1, 7, menu_decel, slide
    animation = specialWorkspaceIn, 1, 2.8, emphasizedDecel, slidevert
    animation = specialWorkspaceOut, 1, 1.2, emphasizedAccel, slidevert
    animation = zoomFactor, 1, 3, standardDecel
}
