# General Configuration
general {
    gaps_in = 4
    gaps_out = 8
    gaps_workspaces = 50
    border_size = 1
    col.active_border = $active_border
    col.inactive_border = $inactive_border
    resize_on_border = true
    no_focus_fallback = true
    allow_tearing = true
    snap {
        enabled = true
        window_gap = 4
        monitor_gap = 5
        respect_gaps = true
    }
}
