misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vrr = 0
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    animate_manual_resizes = false
    animate_mouse_windowdragging = false
    enable_swallow = false
    swallow_regex = ^(foot|kitty|alacritty|Alacritty)$
    allow_session_lock_restore = true
    focus_on_activate = true
}
