hl.on("hyprland.start", function()
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("sleep 5; ~/.config/tsumiki/init.sh -start")
    hl.exec_cmd("hyprpaper --mode fill --stretch --center --scale --blur 0.5 --brightness 1.0 ~/.config/hypr/hyprland/wallpaper.jpg")
    hl.exec_cmd("hypridle --lockscreen ~/.config/hypr/hyprland/lockscreen.sh")
    hl.exec_cmd("waybar")
end)