[urgency_low]
    background = "#111111"
    foreground = "#aaaaaa"
    frame_color = "#333333"
    timeout = 5

[urgency_normal]
    background = "#111111"
    foreground = "#eeeeee"
    frame_color = "#444444"
    timeout = 10

[urgency_critical]
    background = "#111111"
    foreground = "#ffffff"
    frame_color = "#999999"
    timeout = 0
