# Autostart
exec-once = nm-applet --indicator
exec-once = sleep 5; ~/.config/tsumiki/init.sh -start
exec-once = hyprpaper
exec-once = hypridle
exec-once = waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css
