# Source all general configuration components
source = ~/.config/hypr/hyprland/general/general.conf
source = ~/.config/hypr/hyprland/general/decoration.conf
source = ~/.config/hypr/hyprland/general/animations.conf
source = ~/.config/hypr/hyprland/general/input.conf
source = ~/.config/hypr/hyprland/general/gestures.conf
source = ~/.config/hypr/hyprland/general/misc.conf
source = ~/.config/hypr/hyprland/general/layout.conf
source = ~/.config/hypr/hyprland/general/cursor.conf
source = ~/.config/hypr/hyprland/general/xwayland.conf
