# Window Rules

windowrulev2 = border_size 3, floating:1, workspace:w[tv1]
windowrulev2 = rounding 0, floating:1, workspace:w[tv1]

windowrulev2 = border_size 3, floating:1, workspace:f[1]
windowrulev2 = rounding 0, floating:1, workspace:f[1]

windowrulev2 = suppress_event maximize, class:.*

windowrulev2 = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

windowrulev2 = float, class:hyprland-run
windowrulev2 = move 20 monitor_h-120, class:hyprland-run
