# Variables and Colors

# Colors
$background = rgb(111111)
$primary = rgb(cccccc)
$surface = rgb(111111)
$outline = rgb(999999)
$active_border = $primary
$inactive_border = rgba(31313600)
$shadow_color = rgba(00000020)

# App variables
$terminal = ~/.local/bin/launch_first_available.sh 'foot' 'kitty -1' 'alacritty' 'wezterm' 'konsole' 'kgx' 'uxterm' 'xterm'
$fileManager = ~/.local/bin/launch_first_available.sh 'nautilus' 'nemo' 'thunar' 'kitty -1 fish -c yazi'
$browser = ~/.local/bin/launch_first_available.sh 'google-chrome-stable' 'zen-browser' 'firefox' 'brave' 'chromium' 'microsoft-edge-stable' 'opera' 'librewolf'
$menu = wofi --show drun

# Other
$qsConfig = ii
env = qsConfig, $qsConfig
