shell_integration no-cursor
enable_audio_bell no
window_padding_width 5
background_opacity 0.70
background_blur 1
hide_window_decorations yes
confirm_os_window_close 0
# tab bar customization
tab_bar_edge bottom
tab_bar_align left
inactive_tab_font_style normal
