# Monochrome Hyprlock Colors

$text_color = rgba(229, 229, 229, 0.70)
$entry_background_color = rgba(51, 51, 51, 0.92)
$entry_border_color = rgb(0, 0, 0)
$entry_color = rgb(204, 204, 204)
$font_family = JetBrainsMono Nerd Font
$font_family_clock = JetBrainsMono Nerd Font
$font_material_symbols = Material Symbols Rounded
